name: Build NewNeT APK + AAB
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - uses: android-actions/setup-android@v3
      - name: Install dependencies
        run: npm install
      - name: Create android folder (Expo prebuild)
        run: npx expo prebuild --no-install --platform android
      - name: Build APK and AAB
        run: |
          cd android
          chmod +x gradlew
         ./gradlew assembleRelease
         ./gradlew bundleRelease
      - name: Upload APK (for your phone)
        uses: actions/upload-artifact@v4
        with:
          name: NewNeT-APK-Phone
          path: android/app/build/outputs/apk/release/app-release.apk
      - name: Upload AAB (for Play Store)
        uses: actions/upload-artifact@v4
        with:
          name: NewNeT-AAB-PlayStore
          path: android/app/build/outputs/bundle/release/app-release.aab
